Repository facebook/prop-types, pull requests merged in 2019-02, with the labels that each got.

#187 Support validation when hasOwnProperty is not in prototype
  __tests__/PropTypesDevelopmentReact15.js
  __tests__/PropTypesDevelopmentStandalone-test.js
  __tests__/PropTypesProductionReact15-test.js
  checkPropTypes.js
Labels: CLA Signed, Semver: patch

#248 Update README.md
  README.md
Labels: CLA Signed

#178 Export resetWarningCache
  README.md
  __tests__/PropTypesDevelopmentReact15.js
  __tests__/PropTypesDevelopmentStandalone-test.js
  __tests__/PropTypesProductionReact15-test.js
  __tests__/PropTypesProductionStandalone-test.js
  checkPropTypes.js
  factoryWithThrowingShims.js
  factoryWithTypeCheckers.js
Labels: CLA Signed, Semver: minor

#205 missed semicolon
  checkPropTypes.js
Labels: CLA Signed, Semver: patch

#224 Fix oneOf when used with Symbols
  __tests__/PropTypesDevelopmentReact15.js
  __tests__/PropTypesDevelopmentStandalone-test.js
  __tests__/PropTypesProductionReact15-test.js
  factoryWithTypeCheckers.js
Labels: CLA Signed

#204 Completely remove envify in favor of loose-envify
  package.json
  yarn.lock
Labels: CLA Signed, Semver: patch

#217 use componentName in getPropTypeWarningMessage instead of hard-coded testComponent
  __tests__/PropTypesDevelopmentReact15.js
  __tests__/PropTypesDevelopmentStandalone-test.js
Labels: CLA Signed

#244 Warn when multiple arguments were supplied to oneOf
  __tests__/PropTypesDevelopmentReact15.js
  __tests__/PropTypesDevelopmentStandalone-test.js
  factoryWithTypeCheckers.js
Labels: CLA Signed, Semver: patch

#233 Update README.md
  README.md
Labels: CLA Signed

#211 Add a PropTypes for React elementType (ie. MyComponent)
  README.md
  __tests__/PropTypesDevelopmentStandalone-test.js
  __tests__/PropTypesProductionStandalone-test.js
  factoryWithThrowingShims.js
  factoryWithTypeCheckers.js
  index.js
  package.json
  yarn.lock
Labels: CLA Signed, Semver: minor

#258 Update README.md
  README.md
Labels: CLA Signed

#51 Friendlier message when using a type checker that is not a function
  checkPropTypes.js
Labels: CLA Signed, GH Review: review-needed

#234 Fix silently failing invalid validators in shape
  __tests__/PropTypesDevelopmentReact15.js
  __tests__/PropTypesDevelopmentStandalone-test.js
  factoryWithTypeCheckers.js
Labels: CLA Signed, Semver: minor

#262 [Docs] Add instructions for intentional inclusion of validation in production
  README.md
Labels: CLA Signed

#198 Add expected types to oneOfType warning
  __tests__/PropTypesDevelopmentReact15.js
  __tests__/PropTypesDevelopmentStandalone-test.js
  factoryWithTypeCheckers.js
Labels: CLA Signed, Semver: minor
